Balance pass two
sunset-wasteland/sunset-wasteland pull request #414
Opened 2022-09-07 22:30 UTC by ProbablyCarl

- - -
Balance:
 - Assault Carbines nerfed in damage and spread. Significantly. This effects standard and worn.
 - AMR now requires the player to be scoped in, or, with a 95% chance, they'll be stunlocked for firing unprepared.
 - NCR's SEA given a worn assault carbine, rather than standard, identically to the Pointman loadout of Sergeant.
- - -
New:
 - Outcast and Remnant loadouts added to Outlaw. Minor 'unique' stuff for the Remnant has been provided, in both two gimped plasma grenades, and a very meh plasma pistol.
 - Brotherhood Exile role moved to Wastelander.
 - Stuff.
- - -
QoL:
 - Minigun no longer generates casings.
 - Enclave provided with syndicate IDs for espionage purposes.
 - Wiki button renamed from 'TG Wiki' to simply 'Wiki', command updated accordingly.
- - -
Why this includes the pixel shift stuff?
No idea. I swear, sometimes Tortoise Git is wacky like that.
- - -

2022-09-07 22:59 UTC, Spc-Dragonfruits requested changes
Mostly QOL stuff

2022-09-07 22:59 UTC, Spc-Dragonfruits commented on code/game/objects/items/granters.dm
> +	name = "plasma sidearm repair guide"
```suggestion
	name = "plasma pistol field blueprint"
```
For clarity's sake

2022-09-07 22:59 UTC, Spc-Dragonfruits commented on code/game/objects/items/grenades/f13grenade.dm
> +	name = "dusty plasma grenade"
```suggestion
	name = "expired plasma grenade"
```

2022-09-07 22:59 UTC, Spc-Dragonfruits commented on code/modules/projectiles/guns/energy/plasmaf13.dm
> +	name ="lightweight plasma pistol"
```suggestion
	name ="corroded plasma pistol"
```
Clarity's sake, since we got another one

2022-09-08 19:41 UTC, PolymorphBlue approved these changes
Looks fine.

2022-09-08 19:42 UTC, merged