Motorcycles & Madness
sunset-wasteland/sunset-wasteland pull request #437
Opened 2022-09-12 20:42 UTC by ProbablyCarl

- - -
This PR was initially intended to add keycard energy fields to the game, as might be hinted by the branch name. I've discarded that for now, however, and hadn't bothered to change the branch name.
- - -
Balance:
 - Initial introduction of Motorcycles as a faction based object. The NCR gets a Ranger bike, with the key in the Veteran's quarters. The Legion must brave the Renegade camp to get their bike. Otherwise, a rusted bike, with ten percent slowdown, is present in the fire station. That's three bikes in total, one per map. This is likely to be adjusted, as the values for the bikes aren't tweaked and you can snake with them.
 - HMG Mutant given rebalances, post viewing of how it functions in game.
 - Rock Springs firewatch tower given a proper perimeter wall, to make utilizing it as a player base far easier.
- - -
QoL:
 - Legion ORM moved to provide access.
 - Legion given a mining equipment vendor for use with the ORM.
 - Camera console in prison removed.
 - Rooftop added to the shack in Rock Springs, south of the bee farm.
- - -

2022-09-12 21:01 UTC, out-of-phaze requested changes
Some issues with the motorcycle code.

2022-09-12 21:01 UTC, out-of-phaze commented on code/modules/vehicles/_vehicle.dm
>  		usr.visible_message("[usr] start engine of [src].", "You start engine.")
```suggestion
		M.visible_message("[M] starts the engine of [src].", "You start the engine.")
```

2022-09-12 21:01 UTC, out-of-phaze commented on code/modules/vehicles/_vehicle.dm
>  	if(usr)
```suggestion
	if(M)
```

2022-09-12 21:01 UTC, out-of-phaze commented on code/modules/vehicles/_vehicle.dm
>  		usr.visible_message("<span class = 'notice'>There is no key.</span>")
```suggestion
		M.visible_message(span_notice("There is no key."))
```

2022-09-12 21:08 UTC, ProbablyCarl commented
Verb movement was unintentional. Good catch.

2022-09-13 00:37 UTC, out-of-phaze approved these changes
Looks good. TODO: Balance and code quality pass on motorcycles.

2022-09-13 00:37 UTC, merged