removes dogborgs
sunset-wasteland/sunset-wasteland pull request #514
Opened 2022-09-27 13:54 UTC by CDRDecky

should work

if this doesn't i guess the 10 bucks are invalid IDK

2022-09-27 14:48 UTC, IrkallaEpsilon commented
Lyro (Not Lifen) — Today at 1:05 PM
Oh my god why are you making a petition
Comment out line 140 in robot.dm ITS THAT EASY MAKE A PR!!
It literally takes less time to do that than to create a thread about it. Github is also better for discussion on it

FUCK IT BEAT ME TO IT

2022-09-27 15:37 UTC, ExoticJazz commented
Follow the proper PR format, put some effort into it and explain how this contributes to the game.

2022-09-27 15:38 UTC, ExoticJazz requested changes
Follow the proper PR format, put some effort into it and explain how this contributes to the game.

2022-09-27 18:49 UTC, ProbablyCarl commented on code/modules/mob/living/silicon/robot/robot.dm
> +    // 	modulelist += get_cit_modules() //Citadel change - adds Citadel's borg modules.
Improperly commented.

2022-09-28 00:48 UTC, ProbablyCarl commented
There. I got you. That ten dollars is mine, bucko.

2022-09-28 00:57 UTC, merged