Vertibird buff
sunset-wasteland/sunset-wasteland pull request #591
Opened 2022-10-12 10:06 UTC by projectkepler-ru

## About The Pull Request
Work in progress

## Why It's Good For The Game

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-10-12 13:53 UTC, out-of-phaze requested changes
You claimed you documented all your changes but there are a number of undocumented changes.

Also, you alternate between normal and xray cameras, and should probably settle on one. You should make this a subtype in code to avoid all the repeated var edits. You should probably also not use cameras in this way at all.

Also, having view_range set to 250 creates an ungodly amount of lag from `range(250)` and `view(250)` calls. Don't do this.

2022-10-12 13:53 UTC, out-of-phaze commented on _maps/map_files/Pahrump-Sunset/Mountain-Range.dmm
> +/obj/machinery/camera/xray{
Why the fuck is this camera named road and has the sprite of a road?

2022-10-12 13:53 UTC, out-of-phaze commented on _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> +/obj/machinery/camera/xray{
See above. No matter why you're doing this... don't.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +	ADD_TRAIT(H, TRAIT_ABDUCTOR_TRAINING, src)
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> -		/obj/item/grenade/f13/plasma = 2,
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +	ADD_TRAIT(H, TRAIT_UNETHICAL_PRACTITIONER, src)
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +		/datum/outfit/loadout/gysgt_ballistics, // CZ53
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +		/obj/item/minigunpackbal5mm = 1,
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +	suit_store = 	/obj/item/minigunpack
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +	suit_store = /obj/item/gun/energy/laser/aer14
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> -		/obj/item/grenade/f13/plasma = 2,
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +	ADD_TRAIT(H, TRAIT_ABDUCTOR_TRAINING, src)
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> -	H.grant_language(/datum/language/codespeak, TRUE, TRUE, LANGUAGE_MIND)
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +		/datum/outfit/loadout/sgt_laser, 	// Wattz2k
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> -		/obj/item/grenade/f13/plasma = 2,
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +	name = "Laser Support"
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +	ADD_TRAIT(H, TRAIT_ABDUCTOR_TRAINING, src)
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +/*
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> -	H.grant_language(/datum/language/codespeak, TRUE, TRUE, LANGUAGE_MIND)
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> -	H.grant_language(/datum/language/codespeak, TRUE, TRUE, LANGUAGE_MIND)
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +	ADD_TRAIT(H, TRAIT_ABDUCTOR_TRAINING, src)
Undocumented change.

2022-10-12 13:53 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +	name = "vertibird rappel console"
Make this use a trait other than `TRAIT_ABDUCTOR_TRAINING`. You could make the needed trait a var instead, but don't give the Enclave abductor traits.

2022-10-12 13:53 UTC, out-of-phaze commented on _maps/map_files/Pahrump-Sunset/RockSprings.dmm
> +/obj/machinery/camera{
Also, you didn't document these changes in the PR but you ticked that checkbox.

2022-10-12 13:53 UTC, out-of-phaze commented on _maps/map_files/Pahrump-Sunset/RockSprings.dmm
> +	view_range = 250;
NOOOOOO. THIS WILL CREATE AN ABSURD AMOUNT OF LAG.

2022-10-12 13:53 UTC, out-of-phaze commented on _maps/map_files/Pahrump-Sunset/RockSprings.dmm
> +	name = "\proper road";
This clearly doesn't do whatever you think it does. If you hit it, it'll say "you hit road" instead of "you hit the road." Just remove the `\proper`.

2022-10-12 13:53 UTC, out-of-phaze commented on _maps/map_files/Pahrump-Sunset/Mountain-Range.dmm
> +/obj/item/gps,
I don't see this documented anywhere.

2022-10-12 13:53 UTC, out-of-phaze commented on _maps/map_files/Pahrump-Sunset/Mountain-Range.dmm
> +/obj/item/flashlight/flare/emergency,
Is this change actually documented? It doesn't look like it.

2022-10-12 13:57 UTC, out-of-phaze commented on code/modules/jobs/job_types/enclave.dm
> +	ADD_TRAIT(H, TRAIT_ABDUCTOR_TRAINING, src)
Looks like this is documented, but also don't do this. Make the subtype use a separate trait.

2022-10-14 10:47 UTC, Nep993 commented
Those undocumented changes are due to it not being up to date REEEEEEEEEEEEEE

2022-10-19 13:44 UTC, closed without merging