Flatline armor BoS's Nightstalker creation
sunset-wasteland/sunset-wasteland pull request #712
Opened 2022-11-15 17:57 UTC by Moribun

long story made as short as possible. what we talked about in voice. its a slow heal over time armor craftable by scribes made by Flatline  canonically. heals as much as the trauma pack over time and has an auto-defib when dead because the heal continues like the trauma pack did. its loud and obvious. takes time for the defib to happen and even when it does...takes even longer to heal you out of crit....its not an instant pop up and run...your captured or the armor is removed easily. useful for mobs tho.

## About The Pull Request
^ this. also I added a prototype version to my fluff box instead of follower armor. one so I can present it as an IC thing as a prototype...and two...because I like it for when im off duty. one sprite for a patch work prototype exclusive to the night stalker. and then another sprite and craftable one by BOS scribes...flashy and pretty BOS armor colors

## Why It's Good For The Game
its probably not but I made it anyway.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-11-15 18:13 UTC, RadiantFlash7 commented on code/modules/clothing/suits/medium_armor.dm
> +			M.adjustOxyLoss(-2)
This can be removed.

2022-11-15 18:15 UTC, RadiantFlash7 commented on code/modules/clothing/suits/medium_armor.dm
> +		if(M.stat == DEAD)
Make this if(M.stat == DEAD || M.health < M.maxhealth)

2022-11-20 15:45 UTC, Moribun commented
its done. if the armor needs anymore balancing carl lemme know. dropped the rating for it to initiate armor value like radiant suggested and tightened up the code with rayfords help so its less bloaty

2022-11-21 21:18 UTC, out-of-phaze requested changes
Strongly opposed to a number of these changes for balance reasons. Some other minor concerns about code quality etc.

2022-11-21 21:18 UTC, out-of-phaze commented on modular_citadel/code/modules/client/loadout/__donator.dm
> +/obj/item/storage/box/large/custom_kit/moribund_skills/PopulateContents()
No. Don't do this. Don't use `PopulateContents` for things other than populating contents. Make a custom granter book if you want, but don't do this.

2022-11-21 21:18 UTC, out-of-phaze commented on modular_citadel/code/modules/client/loadout/__donator.dm
> +	ADD_TRAIT(P, TRAIT_UNETHICAL_PRACTITIONER_BRAINWASHING, src)// ^
This is given nowhere else in the game. I don't think it's balanced to give it to you roundstart, as any role.

2022-11-21 21:18 UTC, out-of-phaze commented on code/modules/clothing/suits/medium_armor.dm
> +						M.visible_message("<span class='green'>[M]'s suit makes a thump! followed by [M] taking his first breaths again!</span>")
```suggestion
						M.visible_message("<span class='green'>[M]'s suit makes a thump, followed by [M] taking [M.their()] first breaths again!</span>")
```

2022-11-21 21:18 UTC, out-of-phaze commented on code/modules/clothing/suits/medium_armor.dm
> +				M.visible_message("<span class='warning'>[M]'s suit makes a long flatline noise...</span>")
```suggestion
				M.visible_message(span_warning("[M]'s suit makes a long flatline noise..."))
```

2022-11-21 21:18 UTC, out-of-phaze commented on code/modules/clothing/suits/medium_armor.dm
> +	desc = "A modified and refined self-revival 'flatline' armor developed by none other than flatline himself for his pack member he cares so much for. Repainted to the color scheme of the Brotherhood
Is "flatline" a name? If so, capitalize it.
```suggestion
	desc = "A modified and refined self-revival 'flatline' armor developed by none other than Flatline himself for his pack member he cares so much for. Repainted to the color scheme of the Brotherhood of Steel. Its lining inside is a gel-based refinement of the symbiotic algae found in buffalo gourds giving it flesh-mending properties over time. Inside it is a regulated and biomonitor-controlled self-defibrillator unit to bring the host back to life after the gel has done its job."
```

2022-11-21 21:18 UTC, out-of-phaze commented on code/modules/clothing/suits/medium_armor.dm
> +				to_chat(M, "<span class='notice'>You feel your wounds sealing back toghether slowly!</span>")
```suggestion
				to_chat(M, span_notice("You feel your wounds sealing back together slowly!"))
```

2022-11-21 21:18 UTC, out-of-phaze commented on code/modules/clothing/suits/medium_armor.dm
> +	armor = list("melee" = 45, "bullet" = 35, "laser" = 35, "energy" = 35, "bomb" = 35, "bio" = 35, "rad" = 35, "fire" = 35, "acid" = 35, "wound" = 10)
Why does the 'very early model' have more armor than the 'modified and refined' version?

2022-11-21 21:18 UTC, out-of-phaze commented on code/modules/clothing/suits/medium_armor.dm
> +/obj/item/clothing/suit/armored/medium/combat/flatline/prototype/New()
No. Don't use /New() for anything but datums.
```suggestion
/obj/item/clothing/suit/armored/medium/combat/flatline/prototype/Initialize()
```

2022-11-21 21:18 UTC, out-of-phaze commented on code/modules/clothing/suits/medium_armor.dm
> +	..()
Once you change this to initialize you'll need to return parent as well.
```suggestion
	. = ..()
```

2022-11-21 21:18 UTC, out-of-phaze commented on code/modules/clothing/suits/medium_armor.dm
> +	desc = "A very early model of the self-revival 'flatline' armor developed by none other than flatline himself. This one is highly customized. And by customized its cobbled together from junk, drippi
```suggestion
	desc = "A very early model of the self-revival 'flatline' armor developed by none other than Flatline himself. This one is cobbled together from junk, dripping algae, and has a defib unit welded and installed on the chestpiece. It looks like a scav made it."
```

2022-11-21 21:18 UTC, out-of-phaze commented on code/modules/clothing/suits/medium_armor.dm
> +	desc = "A modified and refined self-revival 'flatline' armor developed by none other than flatline himself for his pack member he cares so much for. Repainted to the color scheme of the Brotherhood
Also, highly dislike having character backstory in item descriptions. How would someone know all this just from examining the armor? Especially if they've stolen it, or taken it off of a corpse?

2022-11-21 21:41 UTC, out-of-phaze commented
> ## Changelog
> 
> 🆑 added a 2 heal over time armor that works the same as the trauma backpack it auto defibs on death but takes alot of time for the slow heal to get them to revivable. and even longer before they can stand. revives on the boarder of dead. and takes a long time to heal out of soft crit armor stats are armor = list("melee" = 35, "bullet" = 35, "laser" = 30, "energy" = 20, "bomb" = 25, "bio" = 10, "rad" = 10, "fire" = 20, "acid" = 10, "wound" = 10) (same as initiate armor) and can only be created by scribes and higher rank scribes. tightened up my fluff box to be less book saturated because it was fucking with my OCD so I made it just auto-give the traits when selected /🆑

You also didn't even read the directions on how to use the changelog.
Also, the armor listed is wrong, or more accurately you don't mention *your* armor's stats at all.

2022-11-21 23:39 UTC, Moribun commented
do you want to knock out the few people willing to code? I dont get payed for this I have no proper training. I do it because I was asked, have rudimentary knowledge and no one else was willing too. I have alot to say about you and im not gonna say any of them. but you are seriously making me not want to do this shit anymore.

2022-11-21 23:46 UTC, out-of-phaze commented
> do you want to knock out the few people willing to code? I dont get payed for this I have no proper training. I do it because I was asked, have rudimentary knowledge and no one else was willing too. I have alot to say about you and im not gonna say any of them. but you are seriously making me not want to do this shit anymore.

I literally suggested changes; adding and committing them can be done from the "files changed" view. You just need to add them to the batch and then commit them. It's that easy.

The rest is balance concerns which I'm listing more as a matter of procedure for whoever decides if the PR is merged to look at.

2022-11-21 23:50 UTC, Moribun commented
whatever im done

2022-11-21 23:50 UTC, closed without merging