Elevator Shafts | Various Changes
sunset-wasteland/sunset-wasteland pull request #792
Opened 2022-12-29 11:59 UTC by ProbablyCarl

- - -
### Balance:
 - You can no longer craft magnum shells or flechette outside of specialized roles, in bulk. Instead, you can only craft five at a time, for an obscenely expensive cost. Bulk crafting price increased accordingly.
 - Shotgun stripper clips introduced, in line with the above.
 - Grenade launcher removed from high tier ballistic pool.

  NCR:
   - Combat Engineer has lost their rocket launcher loadout.
   - Heavy trooper can no longer spawn with a flamethrower.
   - LO can bulk craft magnum and flechette rounds.
   - The Scout Carbine has been given 10% penetration.

  Legion:
   - 'Loud' Prime Decanus replaced with 'Demolition' Prime Decanus. This replaces the Grenade Launcher with C4, and compensates by providing two additional frags.
   - Forgemaster can bulk craft magnum and flechette rounds.

  Enclave:
   - Combat Technician has lost their grenade launcher. For now.

  Raiders:
   - Outsider Highwayman now spawns with a revolver.

  Khan
   - Senior Enforcer has once again been given the Neostead, although this time as a unique.
   - Senior Enforcer has lost trekking by default.
- - -
### Map:
 - Legion slave pens should no longer be unroofed.
 - Upper area of the Legion fortress should now be protected from the elements, when in tiles previously occupied by rock.
 - Initial introduction of elevator locations in Bighorn, Vault 113 and Casper's bunker. These are non-functional for now, but you can jump down the elevator shaft for a one way trip. Areas for these additions have been updated thematically.
 - Bighorn received an extra set of stairs to the underground, next to the gate.
   - Poppy's opioid addicted cousin, Skoggy, will now greet visitors, rather than murdering them.
- - -
### Bugfixes:
 - Outsider should no longer spawn nude. Honest mistake. I swear. Probably.
- - -

2022-12-29 12:06 UTC, ProbablyCarl commented
![image](https://user-images.githubusercontent.com/25065997/209948765-39f77ec5-b7fd-4954-b189-c82a953981ed.png)
![image](https://user-images.githubusercontent.com/25065997/209948791-27d54831-b268-4bec-a965-2bf4b083a954.png)
![image](https://user-images.githubusercontent.com/25065997/209948817-f5610750-9e2e-4557-be76-12a693294bf7.png)
![image](https://user-images.githubusercontent.com/25065997/209948840-e5fa750f-d1ea-4d3a-9deb-9445ef2709f8.png)
![image](https://user-images.githubusercontent.com/25065997/209948858-15c46be8-e24a-4fbb-9160-221364f49c6e.png)

2022-12-29 17:55 UTC, SigholtStarsong commented
Is the Shopkeeper going to be able to produce those bunk packages of shells as well?

2022-12-29 22:55 UTC, ProbablyCarl commented
> Is the Shopkeeper going to be able to produce those bunk packages of shells as well?

Added.

2022-12-30 02:59 UTC, Spc-Dragonfruits requested changes

2022-12-30 02:59 UTC, Spc-Dragonfruits commented on code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
> +	/obj/item/stack/sheet/prewar = 50,//Yes, really.
I suggest replacing the pre-war metal requirement with either 2 or 3 polymers (alien alloy), or a pre-war steel ingot

2022-12-30 02:59 UTC, Spc-Dragonfruits commented on code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
> +	/obj/item/stack/sheet/prewar = 30,
Same as above

2022-12-30 02:59 UTC, Spc-Dragonfruits commented on code/modules/projectiles/guns/ballistic/shotgun.dm
> +	desc = "Cold Water, the personalised friend of the Senior Enforcer."
```suggestion
	desc = "A personalized Neostead shotgun belonging to a Senior Enforce of the Great Khans."
```

2022-12-30 02:59 UTC, Spc-Dragonfruits commented on code/modules/jobs/job_types/legion.dm
> +		/obj/item/grenade/f13/frag = 3,
I'd also replace these with HEs instead, to focus on the demolition bit

2022-12-30 03:33 UTC, merged